// <auto-generated />
namespace zadanie3next.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class userLogin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userLogin));
        
        string IMigrationMetadata.Id
        {
            get { return "201610192203527_userLogin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
